### ISSUE TITLE
Javascript Arrays Lab - Broken

### ISSUE THREAD

**Issue by jspradac** [learn-co-curriculum/javascript-arrays-lab#22]
The last test in this lab asks you to  create the function  removeFirstKitten()  which is supposed to remove the first kitten from the kittens array and return a new array, leaving the kittens array unchanged.
 If you do this by means of kittens.slice(1,3) it works.

But if you try to do it by kittens.splice(0,1) it doesn't work. It seems to be treating splice as slice. So kittens.splice(1,3) would work. Seems .splice() is being treated as .slice()

**Comment by drakeltheryuujin** [comment]
Hi @jspradac,

From the attached documentation for `slice()` in the lab:
```The slice() method returns a shallow copy of a portion of an array into a new array object selected from begin to end (end not included). The original array will not be modified.```

The expectation for `removeFirstKitten()` test:
```removes the last kitten in the kittens array and returns a new array, leaving the kittens array unchanged```

The issue here appears to be with your own code. If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
