### ISSUE TITLE
`$ learn submit` not syncing

### ISSUE THREAD

**Issue by jmoglesby** [learn-co-curriculum/javascript-arrays-lab#25]
![image](https://user-images.githubusercontent.com/25443574/58194596-d0a77300-7c7a-11e9-8b6e-ec2ff2baab29.png)

I passed all tests and tried multiple times to `$ learn submit`, but the "Submit" status will not update.

**Comment by maxwellbenton** [comment]
Hi @jmoglesby, 

Sorry to hear that you were experiencing problems with Learn. This issue is due to a bug in Learn, and our engineering team has been notified. If you continue to experience this issue on future lessons, please feel free to reach out to support@learn.co for further assistance.

Thank you!
